Repository PlasmaPy/PlasmaPy-PLEPs, pull requests merged in 2018-10, with the labels that each got.

#8 Add PLEP 5 on versioning and releases
  PLEP-0005.rst
Labels: Status: Voting, Type: Process

#14 Add PLEP 6 on new structure for Plasma class
  PLEP-0000.rst
  PLEP-0006.rst
  README.rst
Labels: Status: Voting, Type: Standard

#23 Add DOIs for PLEPs 5 & 6, and update PLEP template
  PLEP-0000.rst
  PLEP-0001.rst
  PLEP-0005.rst
  PLEP-0006.rst
  PLEP-template.rst
  README.rst
Labels: Archiving, Formatting, Updating information
